name: DNS Block&Redirect Configurer cron task

on:
  schedule:
    - cron: '30 1 * * *' # 04:30 MSK (01:30 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DNS

    env:
      DNS: ${{ vars.DNS }}
      BLOCK: ${{ vars.BLOCK }}
      REDIRECT: ${{ vars.REDIRECT }}

      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

      TZ: Europe/Moscow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run application
        run: |
          echo "Starting application..."
          java --enable-preview -jar target/*.jar

# Настройка DNS директора
  build-director-dns:
    name: Update Director DNS
    runs-on: ubuntu-latest
    environment: DNS_DIRECTOR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run application
        env:
          DNS: ${{ vars.DNS }}
          BLOCK: ${{ vars.BLOCK }}
          REDIRECT: ${{ vars.REDIRECT }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          TZ: Europe/Moscow
        run: |
          echo "Starting application for Director DNS..."
          java --enable-preview -jar target/*.jar
